### ISSUE TITLE
Stop losing workers

### ISSUE THREAD

**Issue by phrazzld** [phrazzld/feedingtube#15]
Unsure of specific steps to reproduce. About ten minutes after a few heavy requests were made on production, the logs show:

```
File "/home/.../billiard/pool.py", line 1224, in mark_as_worker_lost
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL)
```

**Comment by moomooskycow** [comment]
http://phoneask.cc/questions/216875/celery-workerlosterror-worker-exited-prematurely-signal-9-sigkill

Or, if you hate yourself:
https://media.readthedocs.org/pdf/celery/master/celery.pdf

**Comment by moomooskycow** [comment]
Make python and redis oom-killer exceptions:
http://backdrift.org/oom-killer-how-to-create-oom-exclusions-in-linux

And/or switch from Celery to RQ:
http://python-rq.org/

**Comment by moomooskycow** [comment]
Switched to RQ, way simpler to use and manage
