### ISSUE TITLE
Handle extreme quantities of images carefully

### ISSUE THREAD

**Issue by phrazzld** [phrazzld/feedingtube#18]
Even just 500 images can be over a gig zipped. 

Systemically manage S3 storage capacity, server cleanup, etc.

**Comment by moomooskycow** [comment]
1000 image request on production caused LargeZipFile error: Central directory offset would require ZIP64 extension

**Comment by moomooskycow** [comment]
Currently crudely limiting requests to 500 images

**Comment by moomooskycow** [comment]
Using allowZip64=True in ZipFile creation to handle large zipfiles. Still need to build scalable s3 storage management solution (clearing out old junk), but this works for now.
